apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: insurance-service
  name: insurance-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insurance-service
  template:
    metadata:
      labels:
        app: insurance-service
    spec:
      containers:
        - image: insurance_service:latest
          imagePullPolicy: IfNotPresent
          name: insurance-service
          ports:
            - containerPort: 5001
          env:
            - name: "LOAN_SERVICE_URL"
              value: "http://loan-service:5002"
            - name: "ACCOUNT_SERVICE_URL"
              value: "http://account-service:5000"
            - name: "OTEL_EXPORTER_OTLP_TRACES_ENDPOINT"
              value: "http://opentelemetry-collector:4317"
            - name: "OTEL_TRACES_EXPORTER"
              value: "otlp"
            - name: "OTEL_METRICS_EXPORTER"
              value: "none"
            - name: "OTEL_SERVICE_NAME"
              value: "insurance-service"

---
apiVersion: v1
kind: Service
metadata:
  name: insurance-service
spec:
  selector:
    app: insurance-service
  ports:
    - port: 5001
      targetPort: 5001
