config:
  customParsers: |
    [PARSER]
        Name         crijsonparser
        Format       regex
        Regex        ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
        Decode_Field json log

  inputs: |
    [INPUT]
        Name  tail
        Tag   kube.*
        Path  /var/log/containers/*default_non-json-logger*
        Parser crijsonparser

    [INPUT]
        Name  tail
        Tag   fluent-bit*
        Path  /var/log/containers/*default_fluent-bit*
        multiline.parser  docker, cri

  filters: |
    [FILTER]
        Name   kubernetes
        Match  kube.*

    [FILTER]
        Name   expect
        Match  kube.*
        key_exists  request

    [FILTER]
        Name   rewrite_tag
        Match  fluent-bit*
        Rule   log \[error\]\s\[filter:expect:[^\]]+\]\sexception\son\srule\s#[0-9]+\s'key_exists',\skey\s'[^']+'\snot\sfound\. failed.validation true

  outputs: |
    [OUTPUT]
        Name   stdout
        Match  failed.validation

    # [OUTPUT]
    #     name     slack
    #     match    failed.validation
    #     webhook  https://hooks.slack.com/services/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
