config:
  inputs: |
    [INPUT]
            Name  tail
            Tag   kube.*
            Path  /var/log/containers/*logging-fluent-bit_non-json-logger*
            Exclude_Path  /var/log/containers/*logging-fluent-bit_fluent-bit*

    [INPUT]
            Name  tail
            Tag   kube.fluent-bit*
            Path  /var/log/containers/*logging-fluent-bit_fluent-bit*

  filters: |
    [FILTER]
            Name   kubernetes
            Match  kube.*

    [FILTER]
            Name   log_to_metrics
            tag  failed.destination*
            metric_mode  counter
            metric_name  count_all_failed_destinations
            metric_description  This metric counts failed destinations
            Match  kube.fluent-bit*
            regex  log \[.*error.*\].*output=es\.(0|1|2|3|4|5)
  outputs: |

    [OUTPUT]
            Name   es
            Match  kube.*

    [OUTPUT]
            Name   stdout
            Match  failed.destination*

    [OUTPUT]
            name   prometheus_exporter
            match  failed.destination*
            host   0.0.0.0
            port   2020
