apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: account-service
  name: account-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - image: account_service:latest
          imagePullPolicy: IfNotPresent
          name: account-service
          ports:
            - containerPort: 5000
          env:
            - name: "LOAN_SERVICE_URL"
              value: "http://loan-service:5000"
            - name: "INSURANCE_SERVICE_URL"
              value: "http://insurance-service:5000"
            - name: "OTEL_EXPORTER_OTLP_TRACES_ENDPOINT"
              value: "http://opentelemetry-collector:4317"
            - name: "OTEL_TRACES_EXPORTER"
              value: "otlp"
            - name: "OTEL_METRICS_EXPORTER"
              value: "none"
            - name: "OTEL_SERVICE_NAME"
              value: "account-service"
            - name: "OTEL_PROPOGATORS"
              value: "jaeger,tracecontext,baggage"
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  selector:
    app: account-service
  ports:
    - port: 5000
      targetPort: 5000
