apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-debug-container
spec:
  selector:
    matchLabels:
      app: go-debug-container
  template:
    metadata:
      labels:
        app: go-debug-container
    spec:
      containers:
      - name: go-debug-container
        image: sharadregoti/go-debug:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 4040
          - containerPort: 8090
